server:
  port: 8989

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:usersdb;MODE=PostgreSQL
    username: sa
    password:
  h2:
    console:
      path: /db-console
      enabled: true
